export const categoryNameMap = {
  xianxia: "Tiên Hiệp",
  wuxia: "Võ Hiệp",
  fantasy: "Giả Tưởng",
  science_fiction: "Khoa Học Viễn Tưởng",
  sci_fi: "Khoa Học Viễn Tưởng",
  romance: "Lãng Mạn",
  mystery: "Bí Ẩn / Trinh Thám",
  thriller: "Ly Kỳ / Hồi Hộp",
  horror: "Kinh Dị",
  horror_fiction: "Kinh Dị",
  adventure: "Phiêu Lưu",
  historical: "Lịch Sử",
  historical_fiction: "Tiểu Thuyết Lịch Sử",
  drama: "Chính Kịch / Tâm Lý",
  comedy: "Hài Hước",
  children: "Thiếu Nhi",
  children_fiction: "Thiếu Nhi",
  biography: "Tiểu Sử / Hồi Ký",
  autobiography: "Tự Truyện",
  memoir: "Hồi Ký",
  poetry: "Thơ Ca",
  graphic_novel: "Truyện Tranh / Graphic Novel",
  nonfiction: "Phi Hư Cấu / Tài Liệu",
  self_help: "Tự Lực / Kỹ Năng Sống",
  religion: "Tôn Giáo / Tâm Linh",
  science: "Khoa Học",
  art: "Nghệ Thuật",
  music: "Âm Nhạc",
  travel: "Du Lịch",
  cooking: "Ẩm Thực",
  health: "Sức Khỏe",
  psychology: "Tâm Lý",
  philosophy: "Triết Học",
  history: "Lịch Sử",
  classic: "Kinh Điển",
  fiction: "Hư Cấu",
  detective: "Trinh Thám",
  crime: "Tội Phạm / Trinh Thám",
  suspense: "Hồi Hộp / Ly Kỳ",
  action: "Hành Động",
  education: "Giáo Dục",
  sports: "Thể Thao",
  politics: "Chính Trị",
  economics: "Kinh Tế"
};
